# Generated by Django 5.1.3 on 2024-12-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_communitymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_photo',
            field=models.ImageField(blank=True, null=True, upload_to='community_photos/', verbose_name='Community Photo'),
        ),
    ]
