# Generated by Django 5.1.3 on 2024-11-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=200)),
                ('original_url', models.URLField(max_length=1000)),
                ('published_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('ai_summary', models.TextField(blank=True)),
                ('categories', models.JSONField(default=list)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20, null=True)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
    ]
